site_name: lastversion docs
site_description: "Automatic documentation from sources, for lastversion."
site_url: https://lastversion.getpagespeed.com/
repo_url: https://github.com/dvershinin/lastversion
theme:
  name: "material"
  palette:
    scheme: slate
    primary: teal
    accent: purple
  features:
    - navigation.expand
plugins:
  - search
  - mkdocstrings:
      handlers:
        default_handler: python
        python:
          paths: [src]
          setup_commands:
            - import sys
            - sys.path.append("docs")
          selection:
            new_path_syntax: yes
      watch:
        - lastversion
nav:
  - Overview: index.md
  - Code Reference:
    - lastversion.py: reference/lastversion.md
    - version.py: reference/version.md
  - Web API: api.md
  - RPM Auto-Builds:
    - Preparing SPEC files: spec-preparing.md
  - Changelog: changelog.md
  - License: license.md
  - 'Blog': 'https://www.getpagespeed.com/posts'
markdown_extensions:
  - admonition
  - markdown_include.include
  - pymdownx.emoji
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist
  - pymdownx.snippets:
      check_paths: true
  - toc:
      permalink: "¤"
extra:
  generator: false
