name: Deploy docs

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build

    runs-on: ubuntu-20.04

    steps:
      - name: Checkout master
        uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.6'
      - name: Deploy to GH Pages
        uses: mhausenblas/mkdocs-deploy-gh-pages@1.24
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CUSTOM_DOMAIN: lastversion.getpagespeed.com
          REQUIREMENTS: docs/requirements.txt