name: Deploy docs

on:
  release:
    types: [created]

jobs:
  build:
    name: Build

    runs-on: ubuntu-latest

    steps:
      - name: Checkout master
        uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip' # caching pip dependencies will speed up subsequent runs
      - run: pip install -e .
      - run: pip install -r docs/requirements.txt
      - run: mkdocs gh-deploy --force --clean --verbose
